services:
  db:
    image: postgres:latest
    env_file:
      - .env.development
    environment:
      POSTGRES_USER: "devuser"
      POSTGRES_PASSWORD: "devpassword"
      POSTGRES_DB: "devdb"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    environment:
      - APP_ENV=development
    env_file:
      - .env.development
    depends_on:
      - db
    ports:
      - 8080:8080

volumes:
  postgres_data:
