version: '3.8'

services:
  app:
    build:
      context: .
    environment:
      - APP_ENV=production
    env_file:
      - .env.production
    ports:
      - "8080:8080"
    command: ["go", "run", "cmd/main.go"]
